# Generated by Django 3.2.7 on 2021-09-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=250)),
                ('node_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('private', models.BooleanField(default=False)),
                ('html_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owner')),
            ],
        ),
    ]
